# Generated by Django 5.1.4 on 2024-12-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pump', '0002_alter_pump_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pump',
            options={},
        ),
        migrations.RemoveField(
            model_name='pump',
            name='is_wheel_rotating',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='power',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='rotation_speed',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='valve_status',
        ),
        migrations.AddField(
            model_name='pump',
            name='serial_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PumpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('performance', models.FloatField(default=0.0)),
                ('power', models.FloatField(default=0.0)),
                ('rotation_speed', models.FloatField(default=0.0)),
                ('is_wheel_rotating', models.BooleanField(default=False)),
                ('valve_status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=10)),
                ('pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pump.pump')),
            ],
            options={
                'permissions': [('start_pump', 'Can start the pump'), ('stop_pump', 'Can stop the pump')],
            },
        ),
    ]
