# Generated by Django 5.1.4 on 2024-12-29 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pump', '0003_alter_pump_options_remove_pump_is_wheel_rotating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumplog',
            name='pump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Pump.pump'),
        ),
    ]
