# Generated by Django 5.1.4 on 2024-12-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pump', '0004_alter_pumplog_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumplog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default="2024-01-01"),
            preserve_default=False,
        ),
    ]
