# Generated by Django 5.1.4 on 2024-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pump', '0005_pumplog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='wanted_performance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pump',
            name='wanted_rotation_speed',
            field=models.FloatField(default=0.0),
        ),
    ]
